# Issue 解析器配置
issue_parser:
  enabled: true
  repo: xaoxuu/hexo-theme-stellar-showcase # 仓库持有者/仓库名
  sort: updated-desc # 排序，按最近更新，取消此项则按创建时间排序
  label: "active"  # 用于标记有效示例的标签，取消此项则会提取所有 open 状态的 issue
  invalid_label: "invalid"  # 用于标记无效示例的标签
  auto_close: true  # 是否自动关闭无效示例

# 网站检查器配置
site_checker:
  enabled: true
  timeout: 10000  # 请求超时时间（毫秒）
  retry_times: 3  # 重试次数
