name: Site Checker

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  watch:
    types: [started]  # 监听 star 事件

jobs:
  check-sites:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: output
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm install
      - name: Check Sites and Update Labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node scripts/check-sites.js
